version: "2"
services:
  pg:
    image: postgres:10.3
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - POSTGRES_DB=sopds
      - POSTGRES_USER=sopds
      - POSTGRES_PASSWORD=sopds
    volumes:
      - pg-data:/var/lib/postgresql
      - pg-run:/run/postgresql
    command: >
      -c shared_buffers=128MB
      -c work_mem=128MB
      -c maintenance_work_mem=64MB
      -c temp_buffers=128MB
      -c autovacuum=on
      -c synchronous_commit=off
      -c commit_delay=1000
  pgadmin:
    image: fenglc/pgadmin4:latest
    ports:
      - 5050:5050
    links:
      - pg:pg
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASSWORD=admin
    volumes:
      - pg-admin:/var/lib/pgadmin
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sopds:master
    environment:
      - POSTGRES_DB=sopds
      - POSTGRES_USER=sopds
      - POSTGRES_PASSWORD=sopds
      - POSTGRES_HOST=pg
    links:
      - db:db
      - pg:pg
    depends_on:
      - db
      - pg
    ports:
      - 8001:8001
    volumes:
      - "../books:/books"
  scaner:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sopds:master
    environment:
      - POSTGRES_DB=sopds
      - POSTGRES_USER=sopds
      - POSTGRES_PASSWORD=sopds
      - POSTGRES_HOST=pg
    links:
      - db:db
      - pg:pg
    depends_on:
      - db
      - pg
    volumes:
      - "../books:/books"
    command: scaner
volumes:
  pg-data:
  pg-run:
  pg-admin:
